// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-MJcX3UxbgaGpPAyZNsv6ALYiINSc3cA',
    appId: '1:1038623759812:web:ccaf7d11cb9e08c3d99891',
    messagingSenderId: '1038623759812',
    projectId: 'azimutree-256c9',
    authDomain: 'azimutree-256c9.firebaseapp.com',
    storageBucket: 'azimutree-256c9.firebasestorage.app',
    measurementId: 'G-4KRJFYNYB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCORnK1TIkO9qr9g0AJ0hbm-kFsOiVsLtc',
    appId: '1:1038623759812:android:f2c4a049483fc58ed99891',
    messagingSenderId: '1038623759812',
    projectId: 'azimutree-256c9',
    storageBucket: 'azimutree-256c9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGd0J_VGupHPc_sJZW7tR6YNxmWC_iygg',
    appId: '1:1038623759812:ios:5e5ac1a6e55a6c48d99891',
    messagingSenderId: '1038623759812',
    projectId: 'azimutree-256c9',
    storageBucket: 'azimutree-256c9.firebasestorage.app',
    androidClientId: '1038623759812-v6iosp7f39ps0n81d8vir4ncrfvvhf9u.apps.googleusercontent.com',
    iosClientId: '1038623759812-bptuli2rveueibn56au9obo40srhn9qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.azimutree',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGd0J_VGupHPc_sJZW7tR6YNxmWC_iygg',
    appId: '1:1038623759812:ios:5e5ac1a6e55a6c48d99891',
    messagingSenderId: '1038623759812',
    projectId: 'azimutree-256c9',
    storageBucket: 'azimutree-256c9.firebasestorage.app',
    androidClientId: '1038623759812-v6iosp7f39ps0n81d8vir4ncrfvvhf9u.apps.googleusercontent.com',
    iosClientId: '1038623759812-bptuli2rveueibn56au9obo40srhn9qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.azimutree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-MJcX3UxbgaGpPAyZNsv6ALYiINSc3cA',
    appId: '1:1038623759812:web:3702c5b7ff718aa4d99891',
    messagingSenderId: '1038623759812',
    projectId: 'azimutree-256c9',
    authDomain: 'azimutree-256c9.firebaseapp.com',
    storageBucket: 'azimutree-256c9.firebasestorage.app',
    measurementId: 'G-KLD54FNEE3',
  );
}
